create table if not exists public.agenda_share_recipients (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.agenda_share_user_defaults (
  matricula text primary key,
  recipient_emails text[] not null default '{}',
  updated_at timestamptz not null default now()
);

alter table public.agenda_share_recipients enable row level security;
alter table public.agenda_share_user_defaults enable row level security;

drop policy if exists agenda_share_recipients_select on public.agenda_share_recipients;
create policy agenda_share_recipients_select on public.agenda_share_recipients for select to anon, authenticated using (true);

drop policy if exists agenda_share_user_defaults_select on public.agenda_share_user_defaults;
create policy agenda_share_user_defaults_select on public.agenda_share_user_defaults for select to anon, authenticated using (true);

drop policy if exists agenda_share_user_defaults_write on public.agenda_share_user_defaults;
create policy agenda_share_user_defaults_write on public.agenda_share_user_defaults for all to anon, authenticated using (true) with check (true);

grant select on public.agenda_share_recipients to anon, authenticated;
grant select, insert, update, delete on public.agenda_share_user_defaults to anon, authenticated;

insert into public.agenda_share_recipients (name, email, active, sort_order) values
  ('Silvio Almeida', 'silvio.almeida@tracbel.com.br', true, 10),
  ('Janilson Soares', 'janilson.soares@tracbel.com.br', true, 20),
  ('Lutiane Oliveira', 'lutiane.oliveira@tracbel.com.br', true, 30),
  ('Lailson Alves', 'lailson.alves@tracbel.com.br', true, 40),
  ('Daniel Viana', 'daniel.viana@tracbel.com.br', true, 50),
  ('Luciano Mendoca', 'luciano.mendonca@tracbel.com.br', true, 60),
  ('Adriano Batista', 'adriano.gbatista@tracbel.com.br', true, 70),
  ('Antonio Freitas', 'antonio.freitas@tracbel.com.br', true, 80),
  ('Woshington Pacheco', 'woshington.pacheco@tracbel.com.br', true, 90),
  ('Manoel Escorcio', 'manoel.neto@tracbel.com.br', true, 100),
  ('Luiz Liz', 'felipe.liz@tracbel.com.br', true, 110),
  ('Manoel Junior', 'manoel.junior@tracbel.com.br', true, 120)
on conflict (email) do update set
  name = excluded.name,
  active = excluded.active,
  sort_order = excluded.sort_order,
  updated_at = now();
